import {
  HOME_ROUTE,
  ABOUT_ROUTE,
  VANS_ROUTE,
  VANS_DETAIL_ROUTE,
  HOST_ROUTE,
  INCOME_ROUTE,
  REVIEWS_ROUTE,
} from './appRoutes';

import { ALL_VANS_API_ROUTE } from './apiRoutes';

import { VANS_LIST } from './universal';

export {
  HOME_ROUTE,
  ABOUT_ROUTE,
  VANS_ROUTE,
  VANS_DETAIL_ROUTE,
  ALL_VANS_API_ROUTE,
  VANS_LIST,
  HOST_ROUTE,
  INCOME_ROUTE,
  REVIEWS_ROUTE,
};
